/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
              "outline": "#73777F",
              "primary-fixed": "#001C39",
              "surface-container-low": "#F2F4FA",
              "on-primary-container": "#001C39",
              "secondary-fixed-dim": "#004E60",
              "on-surface-variant": "#44474F",
              "secondary-fixed": "#001F28",
              "on-tertiary-container": "#00210C",
              "on-secondary": "#FFFFFF",
              "on-tertiary": "#FFFFFF",
              "surface-container": "#E6E8EF",
              "on-background": "#1A1C22",
              "on-primary": "#FFFFFF",
              "on-secondary-container": "#00566B",
              "on-primary-fixed-variant": "#004883",
              "surface": "#F8F9FF",
              "primary-container": "#1960A6",
              "error": "#BA1A1A",
              "tertiary-container": "#95F5B4",
              "secondary": "#00677F",
              "on-tertiary-fixed": "#00210C",
              "surface-container-highest": "#CED1D9",
              "primary": "#1960A6",
              "tertiary": "#006C36",
              "surface-variant": "#DDE2F0",
              "tertiary-fixed": "#95F5B4",
              "inverse-surface": "#2E3039",
              "on-error": "#FFFFFF",
              "background": "#F8F9FF",
              "surface-dim": "#D9DADF",
              "on-surface": "#1A1C22",
              "on-secondary-fixed-variant": "#004E60",
              "secondary-container": "#C2EEFF",
              "inverse-primary": "#A4C9FF",
              "outline-variant": "#C4C6D0",
              "on-tertiary-fixed-variant": "#005228",
              "surface-container-high": "#DCE0E8",
              "tertiary-fixed-dim": "#79D9A0",
              "on-secondary-fixed": "#001F28",
              "inverse-on-surface": "#F0F0F7",
              "surface-bright": "#F8F9FF",
              "on-error-container": "#410002",
              "primary-fixed-dim": "#A4C9FF",
              "surface-tint": "#1960A6",
              "error-container": "#FFDAD6",
              "on-primary-fixed": "#001C39",
              "surface-container-lowest": "#FFFFFF",
              "warning": "#B45309"
      },
      "borderRadius": {
              "DEFAULT": "0.125rem",
              "lg": "0.25rem",
              "xl": "0.5rem",
              "full": "0.75rem"
      },
      "spacing": {
              "xl": "40px",
              "lg": "24px",
              "container-margin": "32px",
              "md": "16px",
              "sm": "8px",
              "xs": "4px",
              "gutter": "20px",
              "unit": "4px"
      },
      "fontFamily": {
              "body-md": ["Public Sans"],
              "label-caps": ["Inter"],
              "h1": ["Public Sans"],
              "h3": ["Public Sans"],
              "h2": ["Public Sans"],
              "data-tabular": ["Inter"]
      },
      "fontSize": {
              "body-md": ["14px", {"lineHeight": "1.6", "fontWeight": "400"}],
              "label-caps": ["11px", {"lineHeight": "1", "letterSpacing": "0.06em", "fontWeight": "700"}],
              "h1": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
              "h3": ["18px", {"lineHeight": "1.4", "fontWeight": "600"}],
              "h2": ["24px", {"lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600"}],
              "data-tabular": ["13px", {"lineHeight": "1.4", "letterSpacing": "0.01em", "fontWeight": "500"}]
      }
    },
  },
  plugins: [],
}
