import jsPDF from 'jspdf';

export const generateAuditPDF = (villageName, txHash, allocated, received, summary) => {
  const doc = new jsPDF();
  
  // Header
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(24, 95, 165); // Primary blue
  doc.text("CLEARLEDGER", 105, 20, null, null, "center");
  
  doc.setFontSize(14);
  doc.setTextColor(50, 50, 50);
  doc.text("OFFICIAL BLOCKCHAIN AUDIT REPORT", 105, 30, null, null, "center");
  
  // Separator Line
  doc.setDrawColor(200, 200, 200);
  doc.line(20, 35, 190, 35);
  
  // Metadata Section
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("Report Generated:", 20, 45);
  doc.setFont("helvetica", "normal");
  doc.text(new Date().toLocaleString(), 65, 45);
  
  doc.setFont("helvetica", "bold");
  doc.text("Target Entity:", 20, 55);
  doc.setFont("helvetica", "normal");
  doc.text(villageName, 65, 55);
  
  doc.setFont("helvetica", "bold");
  doc.text("Blockchain TxHash:", 20, 65);
  doc.setFont("helvetica", "normal");
  doc.text(txHash, 65, 65);
  
  // Financial Overview Box
  doc.setDrawColor(24, 95, 165);
  doc.setFillColor(245, 248, 252);
  doc.roundedRect(20, 75, 170, 30, 3, 3, "FD");
  
  doc.setFont("helvetica", "bold");
  doc.text("Allocated Budget:", 30, 85);
  doc.text(allocated, 80, 85);
  
  doc.text("Funds Received:", 120, 85);
  doc.text(received, 160, 85);
  
  doc.setFont("helvetica", "normal");
  doc.setTextColor(74, 225, 131); // Green
  doc.text("STATUS: BLOCKCHAIN VERIFIED", 30, 98);
  doc.setTextColor(50, 50, 50);

  // Executive AI Summary
  doc.setFont("helvetica", "bold");
  doc.text("Executive Summary (AI Generated):", 20, 120);
  
  doc.setFont("helvetica", "normal");
  const splitText = doc.splitTextToSize(summary, 170);
  doc.text(splitText, 20, 130);
  
  // Footer
  doc.setFontSize(9);
  doc.setTextColor(150, 150, 150);
  doc.text("This document is auto-generated by the ClearLedger node.", 105, 280, null, null, "center");
  doc.text("Data is immutable and publicly verifiable on the distributed ledger.", 105, 285, null, null, "center");

  // Save the PDF
  doc.save(`${villageName.replace(/\s+/g, '_')}_Audit_Report.pdf`);
};
